In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[0])

[1 2 3 4]


# Array

# Creating Array

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
# You can easily create an array filled with 0s:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# Ora an array filled with 1s:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
# You can create an array with a range of elements
print(np.arange(4))
print(np.arange(0, 10, 2)) # (start, stop, step) 

[0 1 2 3]
[0 2 4 6 8]


In [10]:
# Contoh lain:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

# Add, Remove, and Sort

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Shape and Size

In [16]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                          [[0, 1, 2, 3], 
                          [4, 5, 6, 7]],
                          [[0, 1, 2, 3], 
                           [4, 5, 6, 7]]
                         ])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [18]:
array_example.ndim

3

In [19]:
array_example.size

24

In [20]:
array_example.shape

(3, 2, 4)

In [21]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

# Reshape

In [24]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [25]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [26]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [28]:
# You can use np.newaxis to add a new axis:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [37]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [40]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

# Indexing and Slicing

In [41]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# You can easily print all of the values in the array that are less than 5

print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [47]:
five_up = (a >= 5)

print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [48]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [49]:
# You can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [51]:
a_1 = np.array([[1, 1], 
                [2, 3]])

a_2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 3],
       [3, 3],
       [4, 4]])

In [52]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 3, 4, 4]])

In [53]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [54]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
# Using the copy method will make a complete copy of the array and its data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [58]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [59]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [60]:
# You can sum the rows
b.sum(axis = 0)

array([3, 3])

In [62]:
# You can sum the columns
b.sum(axis = 1)

array([2, 4])

In [63]:
data = np.array([1, 2])
data

array([1, 2])

In [64]:
ones = np.ones(2)
ones

array([1., 1.])

In [65]:
data + ones

array([2., 3.])

In [66]:
data * data

array([1, 4])

In [67]:
data / data

array([1., 1.])

# Broadcasting

In [68]:
data * 2

array([2, 4])

# More Array Operations

In [69]:
A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
A.sum()

78

In [71]:
A.min()

1

In [72]:
A.min(axis = 0)

array([1, 2, 3, 4])

In [73]:
A.max()

12

In [74]:
A.max(axis = 1)

array([ 4,  8, 12])

In [75]:
A.std()

3.452052529534663

# Matrices

In [77]:
np.ones((3, 2))
np.zeros((3, 2))
np.random.random((3, 2))

print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(np.random.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.43781728 0.71228436]
 [0.39266118 0.52288392]
 [0.26341029 0.88068698]]


# Matrix Arithmetic

In [78]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [79]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [80]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [82]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [83]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [85]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [86]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [88]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [89]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [90]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [91]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [92]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [95]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [97]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [103]:
ndarr = np.array([[[1,2], [3,4]],
                [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [104]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [105]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [106]:
print(np.random.random((4, 3, 2)))

[[[0.73250637 0.1932184 ]
  [0.75764078 0.37402971]
  [0.76767176 0.14526275]]

 [[0.57511781 0.18844764]
  [0.94893412 0.83366295]
  [0.21512391 0.22530101]]

 [[0.81201097 0.41021073]
  [0.84495216 0.32526236]
  [0.3030381  0.4194151 ]]

 [[0.03395716 0.3894022 ]
  [0.97133783 0.47944037]
  [0.59800224 0.90062728]]]


# Filter N-Dimensional Array

In [107]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [108]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Working with Math Formulas

error = (1/n) * np.sum(np.square(observed - prediction))